apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-deployment
  labels:
    role: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: java-app
  template:
    metadata:
      labels:
        role: java-app
    spec:
      containers:
      - name: java-app
        image: JUSTIMAGEPLACEHOLDER
        resources:
          requests:
            cpu: 10m
